apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysqlha.configmap" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- range $key, $val := .Values.mysqlConfig }}
  {{- if eq $key "master.cnf" }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end}}
{{- end }}
  {{- range $key, $val := .Values.mysqlConfig }}
  {{- if eq $key "slave.cnf" }} 
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
  server-id.cnf: |
    [mysqld]
    server-id=@@SERVER_ID@@
  create-replication-user.sql: |
    CREATE USER IF NOT EXISTS '@@REPLICATION_USER@@' IDENTIFIED BY '@@REPLICATION_PASSWORD@@';
    GRANT PROCESS, RELOAD, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '@@REPLICATION_USER@@';
    FLUSH PRIVILEGES;
