# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app-name: {{ template "fullname" . }}
    app-replicas: {{ .Values.replicaCount | quote }}
    type: mysqlha
{{ include "mysqlha.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ template "fullname" . }}
    port: 3306
  selector:
    type: mysqlha
{{ include "mysqlha.labels" . | indent 4 }}
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-readonly
  labels:
    app-name: {{ template "fullname" . }}
    type: mysqlha
{{ include "mysqlha.labels" . | indent 4 }}
spec:
  ports:
  - name: {{ template "fullname" . }}
    port: 3306
  selector:
    type: mysqlha
{{ include "mysqlha.labels" . | indent 4 }}
